# docker-compose.yml
version: '3.8'

services:
  mlflow:
    image: burakince/mlflow:latest
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 --port 5000
    volumes:
      - ./mlruns:/mlruns
      - ./mlflow.db:/mlflow.db
    ports:
      - "5000:5000"
    environment:
      - GIT_PYTHON_REFRESH=quiet

  mlproject:
    build: .
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - GIT_PYTHON_REFRESH=quiet
    depends_on:
      - mlflow
